### ISSUE TITLE
You have exhausted the account limits per ip

### ISSUE THREAD

**Issue by Suflet0** [nickuc/OpeNLogin#55]

**Comment by nickuc** [comment]
Hi, @Suflet0!

Change the limit option in your config.yml:
```yml
  # Prohibits a user with the same ip address from registering many times.
  address-limiter:
    enable: true

    # Sets maximum number of login/registers by an ip address.
    limit: 3
```
